diff -dur Zope-2.7.0.orig/lib/python/Zope/Startup/__init__.py Zope-2.7.0/lib/python/Zope/Startup/__init__.py
--- Zope-2.7.0.orig/lib/python/Zope/Startup/__init__.py	2004-01-09 00:34:05.000000000 +0100
+++ Zope-2.7.0/lib/python/Zope/Startup/__init__.py	2004-02-13 15:37:51.114975401 +0100
@@ -343,8 +343,8 @@
         raise ZConfig.ConfigurationError(msg)
 
     try:
-        import initgroups
-        initgroups.initgroups(effective_user, gid)
+        zLOG.LOG("Zope", zLOG.INFO,
+			'Warning: not calling initgroups() as it seems broken.')
         os.setgid(gid)
     except OSError:
         zLOG.LOG("Zope", zLOG.INFO,
Only in Zope-2.7.0/lib/python/Zope/Startup: __init__.py~
